### ISSUE TITLE
SC_01 - As a developer, I want a visualization of the SCCP protocol, so that I can simulate different scenarios

### ISSUE THREAD

**Issue by Bart2000** [Bart2000/StackCabinet#1]
**DoD**
- [x] Write StackCabinet Control Protocol
- [x] Visualize with java to cover scenarios

**Comment by Bart2000** [comment]
Cool

**Comment by Krakert** [comment]
[USART in One-Wire Mode](https://ww1.microchip.com/downloads/en/AppNotes/USART-in-One-Wire-Mode-ApplicationNote-DS00002658.pdf)
